name: 'Install Dependencies'
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  install:
    name: 'Install and Cache PowerShell Modules'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Setup Cache'
        id: PSCache
        uses: actions/cache@v4
        with:
          path: PSCache
          key: PSCache-${{ runner.os }}-Dependencies
          enableCrossOsArchive: true
      - name: 'Trust PSGallery'
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
      - name: 'Install Modules'
        if: steps.PSCache.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -ErrorAction Stop

