name: Lint
on: [push, pull_request, workflow_dispatch]
jobs:
  lint:
    name: Run PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          path: .\PSProfileTools\
          # customRulePath: .\tests\ScriptAnalyzerSettings.psd1
          # fix: true
          recurse: true
          output: 'psscriptanalyzer.log.sarif'
